In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("triagem_sintetica.csv")
df.head()

,idade,idade_risco,tosse,pieira,dor_garganta,congestao_nasal,agravamento,duracao_prolongada,doenca_respiratoria_previa,imunossupressao,...,dificuldade_respiratoria_moderada,dificuldade_respiratoria_grave,dor_toracica_nenhuma,dor_toracica_ligeira,dor_toracica_moderada,dor_toracica_forte,limitacao_respiratoria_nenhuma,limitacao_respiratoria_alguma,limitacao_respiratoria_significativa,encaminhamento
0,35,0,1,1,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
1,29,0,0,0,1,0,0,1,1,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
2,89,1,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,consulta_medica
3,62,0,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
4,83,1,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,consulta_medica

In [17]:
df.shape

(1000, 25)

In [18]:
df.columns.tolist()

['idade',
 'idade_risco',
 'tosse',
 'pieira',
 'dor_garganta',
 'congestao_nasal',
 'agravamento',
 'duracao_prolongada',
 'doenca_respiratoria_previa',
 'imunossupressao',
 'febre_nenhuma',
 'febre_moderada',
 'febre_alta',
 'dificuldade_respiratoria_nenhuma',
 'dificuldade_respiratoria_ligeira',
 'dificuldade_respiratoria_moderada',
 'dificuldade_respiratoria_grave',
 'dor_toracica_nenhuma',
 'dor_toracica_ligeira',
 'dor_toracica_moderada',
 'dor_toracica_forte',
 'limitacao_respiratoria_nenhuma',
 'limitacao_respiratoria_alguma',
 'limitacao_respiratoria_significativa',
 'encaminhamento']

In [19]:
df.isnull().sum()

idade                                   0
idade_risco                             0
tosse                                   0
pieira                                  0
dor_garganta                            0
congestao_nasal                         0
agravamento                             0
duracao_prolongada                      0
doenca_respiratoria_previa              0
imunossupressao                         0
febre_nenhuma                           0
febre_moderada                          0
febre_alta                              0
dificuldade_respiratoria_nenhuma        0
dificuldade_respiratoria_ligeira        0
dificuldade_respiratoria_moderada       0
dificuldade_respiratoria_grave          0
dor_toracica_nenhuma                    0
dor_toracica_ligeira                    0
dor_toracica_moderada                   0
dor_toracica_forte                      0
limitacao_respiratoria_nenhuma          0
limitacao_respiratoria_alguma           0
limitacao_respiratoria_significativa    0
encaminhamento                          0
dtype: int64

In [20]:
df["encaminhamento"].value_counts()

encaminhamento
consulta_medica    669
emergencia         149
urgencia           142
autocuidados        40
Name: count, dtype: int64

In [21]:
df["encaminhamento"].value_counts(normalize=True) * 100

encaminhamento
consulta_medica    66.9
emergencia         14.9
urgencia           14.2
autocuidados        4.0
Name: proportion, dtype: float64

In [25]:
df[df["encaminhamento"] == "autocuidados"].head(10)

,idade,idade_risco,tosse,pieira,dor_garganta,congestao_nasal,agravamento,duracao_prolongada,doenca_respiratoria_previa,imunossupressao,...,dificuldade_respiratoria_moderada,dificuldade_respiratoria_grave,dor_toracica_nenhuma,dor_toracica_ligeira,dor_toracica_moderada,dor_toracica_forte,limitacao_respiratoria_nenhuma,limitacao_respiratoria_alguma,limitacao_respiratoria_significativa,encaminhamento
6,29,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
10,30,0,0,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
30,15,0,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
40,28,0,0,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
57,22,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
59,62,0,0,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
65,21,0,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
72,22,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
82,61,0,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados
108,39,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,autocuidados

In [27]:
df[df["encaminhamento"] == "consulta_medica"].head(10)

,idade,idade_risco,tosse,pieira,dor_garganta,congestao_nasal,agravamento,duracao_prolongada,doenca_respiratoria_previa,imunossupressao,...,dificuldade_respiratoria_moderada,dificuldade_respiratoria_grave,dor_toracica_nenhuma,dor_toracica_ligeira,dor_toracica_moderada,dor_toracica_forte,limitacao_respiratoria_nenhuma,limitacao_respiratoria_alguma,limitacao_respiratoria_significativa,encaminhamento
0,35,0,1,1,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
1,29,0,0,0,1,0,0,1,1,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
2,89,1,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,consulta_medica
3,62,0,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,consulta_medica
4,83,1,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,consulta_medica
7,53,0,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,consulta_medica
8,61,0,1,0,1,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,consulta_medica
9,28,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,consulta_medica
11,61,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,consulta_medica
12,73,1,0,0,1,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,consulta_medica

In [29]:
df[df["encaminhamento"] == "urgencia"].head(10)

,idade,idade_risco,tosse,pieira,dor_garganta,congestao_nasal,agravamento,duracao_prolongada,doenca_respiratoria_previa,imunossupressao,...,dificuldade_respiratoria_moderada,dificuldade_respiratoria_grave,dor_toracica_nenhuma,dor_toracica_ligeira,dor_toracica_moderada,dor_toracica_forte,limitacao_respiratoria_nenhuma,limitacao_respiratoria_alguma,limitacao_respiratoria_significativa,encaminhamento
5,90,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,urgencia
28,49,0,0,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,1,0,urgencia
34,18,0,1,0,1,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,urgencia
53,82,1,1,0,1,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,urgencia
66,78,1,0,0,0,1,1,0,0,0,...,1,0,0,1,0,0,0,1,0,urgencia
67,4,1,1,0,1,1,1,0,0,0,...,0,0,0,1,0,0,1,0,0,urgencia
71,32,0,1,0,1,0,0,0,1,0,...,1,0,0,0,1,0,0,1,0,urgencia
77,75,1,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,urgencia
85,76,1,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,urgencia
92,46,0,1,1,0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,0,urgencia

In [31]:
df[df["encaminhamento"] == "emergencia"].head(10)

,idade,idade_risco,tosse,pieira,dor_garganta,congestao_nasal,agravamento,duracao_prolongada,doenca_respiratoria_previa,imunossupressao,...,dificuldade_respiratoria_moderada,dificuldade_respiratoria_grave,dor_toracica_nenhuma,dor_toracica_ligeira,dor_toracica_moderada,dor_toracica_forte,limitacao_respiratoria_nenhuma,limitacao_respiratoria_alguma,limitacao_respiratoria_significativa,encaminhamento
14,37,0,0,1,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,1,emergencia
18,33,0,1,0,0,1,0,1,1,0,...,1,0,1,0,0,0,0,0,1,emergencia
19,38,0,0,1,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,1,emergencia
23,0,1,1,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,emergencia
26,77,1,1,0,1,1,0,0,0,0,...,1,0,1,0,0,0,0,0,1,emergencia
27,41,0,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,emergencia
32,69,1,1,1,1,1,0,0,0,0,...,1,0,1,0,0,0,0,0,1,emergencia
44,49,0,1,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,1,emergencia
45,21,0,0,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,1,emergencia
60,16,0,0,0,1,1,0,0,1,0,...,1,0,0,1,0,0,0,0,1,emergencia

In [32]:
df["tosse"].value_counts()

tosse
1    592
0    408
Name: count, dtype: int64

In [33]:
df["encaminhamento"].value_counts()

encaminhamento
consulta_medica    669
emergencia         149
urgencia           142
autocuidados        40
Name: count, dtype: int64